"""Freeze the exp5_cap_only budget grid from the calibration decision.

Reads ``results/exp5_cap_only/calibration/<writer>/calibration.json`` - the
output of ``analyse_exp5_calibration.py`` applying the pre-registered rule -
and, only if that decision is clean, writes ``configs/exp5_cap_only_frozen_config.yaml``:
the template config with the six budgets filled in, ``frozen: true``, the
headline corpora recorded under ``cohort.corpora``, and a provenance block
naming the calibration run and a hash of the decision it came from.

A corpus without a useful region is left out of ``cohort.corpora``. It is a
boundary condition, already measured by the calibration run under the same
protocol, and is not rerun at full scale.

Refuses, with a non-zero exit, when:
  - the decision carries a flag (no region anywhere, non-overlapping regions,
    or a region too narrow for six distinct budgets) - those need a person;
  - the grid does not have exactly six budgets;
  - a frozen config already exists - freezing happens once.

    python src/freeze_exp5_budgets.py --writer mistral24
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = "configs/exp5_cap_only_config.yaml"
FROZEN = "configs/exp5_cap_only_frozen_config.yaml"
HEADER = """# GENERATED by src/freeze_exp5_budgets.py from the pre-registered calibration
# rule. Do not edit by hand: the protocol hash of every main-run output depends
# on this file's contents, so a change here strands those outputs. To refreeze,
# delete this file deliberately and rerun the calibration analysis.
"""


def freeze(decision_path: Path, template_path: Path, out_path: Path,
           job_id: str | None = None) -> dict:
    if out_path.exists():
        raise SystemExit(f"{out_path.name} already exists; freezing happens once")
    raw = decision_path.read_bytes()
    record = json.loads(raw)
    decision = record["decision"]
    if decision.get("flag"):
        raise SystemExit(f"calibration flagged, not freezing: {decision['flag']}")
    grid = decision.get("grid")
    count = record["rule"]["count"]
    if not grid or len(grid) != count:
        raise SystemExit(f"expected {count} budgets, got {grid}")
    if not decision.get("headline"):
        raise SystemExit("no headline corpus in the decision")

    cfg = yaml.safe_load(template_path.read_text(encoding="utf-8"))
    if cfg["budgets"].get("frozen"):
        raise SystemExit(f"{template_path.name} is already marked frozen; it must stay the template")
    frozen = copy.deepcopy(cfg)
    frozen["budgets"]["absolute"] = [int(b) for b in grid]
    frozen["budgets"]["frozen"] = True
    frozen["budgets"]["calibrated_from"] = {
        "calibration_run": record["run_dir"],
        "decision_file": str(decision_path.relative_to(ROOT)).replace("\\", "/"),
        "decision_sha256": hashlib.sha256(raw).hexdigest(),
        "rule_in_run_manifest": record.get("rule_in_run_manifest"),
        "headline": decision["headline"],
        "regions": decision["regions"],
        "frozen_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "freeze_job": job_id,
    }
    frozen["cohort"]["corpora"] = list(decision["headline"])
    out_path.write_text(HEADER + yaml.safe_dump(frozen, sort_keys=False), encoding="utf-8")
    return frozen


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--writer", default="mistral24")
    parser.add_argument("--decision", default="")
    parser.add_argument("--template", default=TEMPLATE)
    parser.add_argument("--out", default=FROZEN)
    parser.add_argument("--job-id", default=None)
    args = parser.parse_args()
    decision = Path(args.decision) if args.decision else (
        ROOT / "results/exp5_cap_only/calibration" / args.writer / "calibration.json")
    frozen = freeze(decision, ROOT / args.template, ROOT / args.out, args.job_id)
    print(json.dumps({"frozen": True, "budgets": frozen["budgets"]["absolute"],
                      "corpora": frozen["cohort"]["corpora"], "config": args.out}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
